name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Create tarball
        run: |
          tar -czf uc-intg-onkyo-avr-${{ github.ref_name }}.tar.gz .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: uc-intg-onkyo-avr-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
